### PR TITLE
universal intrinsic for SIFT

### PR DESCRIPTION
**Pull request by Yosshi999**
rebased version

### CODE REVIEW

**Comment by Yosshi999** [comment]
<details>
<summary>Test cases</summary>
<pre>
feature2d_detect.
  detect/57  # GetParam() = (SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")
  detect/58  # GetParam() = (SIFT_DEFAULT, "stitching/a3.png")
  detect/59  # GetParam() = (SIFT_DEFAULT, "stitching/s2.jpg")
feature2d_extract.
  extract/18  # GetParam() = (SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")
  extract/19  # GetParam() = (SIFT_DEFAULT, "stitching/a3.png")
  extract/20  # GetParam() = (SIFT_DEFAULT, "stitching/s2.jpg")
feature2d_detectAndExtract.
  detectAndExtract/18  # GetParam() = (SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")
  detectAndExtract/19  # GetParam() = (SIFT_DEFAULT, "stitching/a3.png")
  detectAndExtract/20  # GetParam() = (SIFT_DEFAULT, "stitching/s2.jpg")
</pre>
</details>

<details>
<summary>Performance for SSE2 baseline</summary>

Performace test | Reference time | PR time | Speedup
--|--|--|--
detect/57 | 110.77 | 110.82 | 0.999549
detect/58 | 103.91 | 102.08 | 1.017927
detect/59 | 221.66 | 218.72 | 1.013442
extract/18 | 68.4 | 61.09 | 1.11966
extract/19 | 46.52 | 42.5 | 1.094588
extract/20 | 206.91 | 180.9 | 1.143781
detectAndExtract/18 | 160.03 | 149.95 | 1.067222
detectAndExtract/19 | 184.96 | 170.37 | 1.085637
detectAndExtract/20 | 435.27 | 397.29 | 1.095598
</details>

<details>
<summary>Performance for SSE3 baseline</summary>

Performance test | Reference time | PR time | Speedup
-- | -- | -- | --
detect/57 | 109.4 | 108.8 | 1.005515
detect/58 | 103.53 | 101.53 | 1.019699
detect/59 | 221.11 | 214.64 | 1.030143
extract/18 | 69.48 | 61.42 | 1.131228
extract/19 | 47.06 | 42.83 | 1.098763
extract/20 | 211.52 | 181.71 | 1.164053
detectAndExtract/18 | 159.5 | 149.9 | 1.064043
detectAndExtract/19 | 184.8 | 170.27 | 1.085335
detectAndExtract/20 | 438.35 | 398.1 | 1.101105
</details>

<details>
<summary>Performance for SSE4.2 baseline</summary>

Performance test | Reference time | PR time | Speedup
-- | -- | -- | --
detect/57 | 111.3 | 108.26 | 1.028081
detect/58 | 104.05 | 101.76 | 1.022504
detect/59 | 220.64 | 230.93 | 0.955441
extract/18 | 69.47 | 59.24 | 1.172687
extract/19 | 47.29 | 41.35 | 1.143652
extract/20 | 211.78 | 174.29 | 1.215101
detectAndExtract/18 | 160.09 | 147.61 | 1.084547
detectAndExtract/19 | 186.66 | 167.1 | 1.117056
detectAndExtract/20 | 439.57 | 405.87 | 1.083032
</details>

<details>
<summary>Performance for AVX2 baseline</summary>

Performance test | Reference time | PR time | Speedup
-- | -- | -- | --
detect/57 | 105.27 | 105.53 | 0.997536
detect/58 | 97.97 | 98.5 | 0.994619
detect/59 | 208.17 | 211.63 | 0.983651
extract/18 | 52.31 | 53.26 | 0.982163
extract/19 | 37.25 | 37.68 | 0.988588
extract/20 | 150.7 | 153.38 | 0.982527
detectAndExtract/18 | 138.54 | 140.22 | 0.988019
detectAndExtract/19 | 152.58 | 155.6 | 0.980591
detectAndExtract/20 | 358.02 | 359.65 | 0.995468
</details>

**Comment by terfendail** [comment]
I've added a few comments to the main repository PR. Some of them address possible performance change so could you please check them.

**Comment by terfendail** [comment]
BufferArea change looks fine for me. Could you please create PR to the main repository?

**Comment by terfendail** [comment]
All the changes are already integrated to main OpenCV repository

**Pull request closed without merging**
